name: WhosFishing
version: '${project.version}'
main: net.quitrindev.fishing.WhosFishing
api-version: '1.20'
commands:
  whosfishing:
    aliases: [ fishers, fish ]
    description: Who's fishing at the moment on the server
    usage: /<command>